### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by kazu-yamamoto** [http2jp/http2-frame-test-case#1]
- Error frame cannot be expressed in JSON in general.
- So, "frame" and "error" should be alternative.
- Both "frame" and "error" can be null. If one is an object, the other must be null.
- Error frame JSONs should be stored in "error". It may not have a illegal frame type.
- "description" in "error" should be removed. Use the top-level "description", instead.

**Comment by kazu-yamamoto** [comment]
- Q) All settings values are assumed default, right?
- Q) Is "headers" in the headers frame just hex string? We cannot parse headers because we don't have context here.
- Q) Is the exclusive flag a separate key from stream identifier like "exclusive"?
- e.g)  "priority" = { "exclusive": true, "stream_dependency": 10, "weight": 20 }

**Comment by kazu-yamamoto** [comment]
- We decode "wire" by our parser
- If succeeds, we compare the decoded result with "frame"
- Otherwise, we look up the error in "error"

**Comment by tatsuhiro-t** [comment]
> Q) All settings values are assumed default, right?

Do we need "context" of default settings in the first place?

> Q) Is "headers" in the headers frame just hex string? We cannot parse headers because we don't have context here.

Yes. It is not intended to be decoded by HPACK. Just chunk of opaque blob.

> Q) Is the exclusive flag a separate key from stream identifier like "exclusive"?

Yes.
