### ISSUE TITLE
Header cases are wrong

### ISSUE THREAD

**Issue by grosch** [http2jp/http2-frame-test-case#10]
https://github.com/http2jp/http2-frame-test-case/blob/5c67db0d4d68e1fb7d3a241d6e01fc04d981f465/headers/normal.json#L9

You can't send a string block like this.  The header block is supposed to be an RFC7541 encoded header block.  So in your example you should have a data string of `000027010000000001830F10106170706C69636174696F6E2D6A736F6E0F04106170706C69636174696F6E2D6A736F6E` if you pass in headers of:

- :method:POST
- Content-Type:application-json
- Accept:application-json

**Comment by grosch** [comment]
Of course if you're using Huffman encoding instead of string literals then the data block would be `00000D010000000001830F108370947F0F048370947F`

**Comment by kazu-yamamoto** [comment]
Most Japanse people are now enjoying a long winter vacation.
We will resume our programming activity after 8th Jan (a national holiday).
Please wait for a while.

**Comment by kazu-yamamoto** [comment]
This is a test case only for headers excluding their body.

**Comment by grosch** [comment]
You should make that explicit in the test "doc" then, and don't put a header_block_fragment as it makes it look like that's what you're using.
