### ISSUE TITLE
priority

### ISSUE THREAD

**Issue by kazu-yamamoto** [http2jp/http2-frame-test-case#5]
Priority (exclusive/stream dependency/weight) may be contained in the headers frame.
The Priority frame contains this triple, of course.

Currently, I treat this as a structure:

``` json
        "frame_payload": {
            "priority": {
                "stream_dependency": 11,
                "weight": 8,
                "exclusive": false
            }
        },
```

This make sense for the headers frame because each property cannot stand alone. For example, we can express `"priority": null` in the headers frame.

But for the priority frame, this is a bit redundant.

@jblazquez which do you like, flat one or structured one shown above?

**Comment by tatsuhiro-t** [comment]
I slightly lean towards flat one, since priority data is mandatory for PRIORITY frame.
But I can live with either way.

**Comment by jblazquez** [comment]
I don't have a preference. Either works for me.

**Comment by kazu-yamamoto** [comment]
OK. So, I will flatten priority. This more matches the frame definitions in the HTTP/2 spec.

If the priority fields conflict in JSON, let's take it that the test case data is broken. (e.g. `stream_dependency` is non-null but `weight` is null.)
