### ISSUE TITLE
Push-promise with invalid padding case has incomplete error list

### ISSUE THREAD

**Issue by danielkza** [http2jp/http2-frame-test-case#7]
The case in `error/push_promise-frame-padding.json`:

```
Length: 00 00 04
Type: 05
Flags: 08
Stream ID: 00 00 00 01
Padding Length: 04
Padding: AA AA AA
```

Only has an acceptable error code of `PROTOCOL_ERROR`, but it seems to me that `FRAME_SIZE_ERROR` is also valid. The fact that the `PADDED` flag is set means the payload must be at least 5 bytes long, but it is only 4, which seems like a valid reason to reject immediately according to Section 4.2 of the RFC:

> An endpoint MUST send an error code of FRAME_SIZE_ERROR if a frame exceeds the size defined in SETTINGS_MAX_FRAME_SIZE, exceeds any limit defined for the frame type, **or is too small to contain mandatory frame data**.

**Comment by kazu-yamamoto** [comment]
Right. Would you give us a pull request?

**Comment by danielkza** [comment]
Done :)
